import { prisma } from '@/lib/prisma'

export const metadata = {
  title: 'Audit Trail | GroundedVote',
  description: 'Every question GroundedVote has generated, every bias score, every variant — public and archived.',
}

export const revalidate = 300 // refresh every 5 minutes

async function getAuditData() {
  try {
    const questions = await prisma.question.findMany({
      where: { auditStatus: 'APPROVED' },
      include: {
        race: { select: { label: true, state: true, chamber: true } },
        variants: { orderBy: { biasScore: 'asc' } },
        position: { select: { stance: true, sourceType: true } },
      },
      orderBy: { createdAt: 'desc' },
      take: 200,
    })
    return questions
  } catch {
    return []
  }
}

const TOPIC_LABELS = {
  HEALTHCARE: 'Healthcare', ECONOMY: 'Economy', IMMIGRATION: 'Immigration',
  ENVIRONMENT: 'Environment', EDUCATION: 'Education', HOUSING: 'Housing',
  CRIMINAL_JUSTICE: 'Criminal Justice', FOREIGN_POLICY: 'Foreign Policy',
  VOTING_RIGHTS: 'Voting Rights', SOCIAL_SECURITY: 'Social Security',
  DRUG_POLICY: 'Drug Policy', GUN_POLICY: 'Gun Policy', LABOR: 'Labor',
  TAXES: 'Taxes', VETERANS: 'Veterans', INFRASTRUCTURE: 'Infrastructure',
  TECHNOLOGY: 'Technology', OTHER: 'Other',
}

function BiasBar({ label, value }) {
  if (value == null) return null
  const color = value < 15 ? '#81C784' : value < 30 ? '#D8AB69' : '#E57373'
  return (
    <div style={{ marginBottom: 6 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
        <span style={{ color: 'rgba(245,240,232,0.45)', fontSize: 11 }}>{label}</span>
        <span style={{ color, fontSize: 11, fontWeight: 700 }}>{Math.round(value)}</span>
      </div>
      <div style={{ height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.08)' }}>
        <div style={{ width: `${Math.min(value, 100)}%`, height: '100%', borderRadius: 2, backgroundColor: color, transition: 'width 0.8s' }} />
      </div>
    </div>
  )
}

export default async function AuditPage() {
  const questions = await getAuditData()

  return (
    <>
      <section style={{ backgroundColor: '#0F1B1F', padding: '96px 24px 60px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <p style={{ color: '#D8AB69', fontSize: 10, fontWeight: 700, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: 16 }}>Public Audit Trail</p>
          <h1 style={{ color: '#F5F0E8', fontSize: 'clamp(28px, 4vw, 48px)', fontWeight: 300, lineHeight: 1.15, letterSpacing: '-0.02em', marginBottom: 16 }}>
            Every question. Every score.<br />Nothing hidden.
          </h1>
          <p style={{ color: 'rgba(245,240,232,0.5)', fontSize: 17, lineHeight: 1.7, maxWidth: 580, marginBottom: 8 }}>
            This is the complete archive of every question generated by the GroundedVote bias-audit pipeline. Every variant, every bias score, every selection decision — public and permanent.
          </p>
          <p style={{ color: 'rgba(245,240,232,0.3)', fontSize: 13 }}>
            {questions.length} approved questions archived · Updated continuously
          </p>
        </div>
      </section>

      {/* Methodology reminder */}
      <section style={{ backgroundColor: 'rgba(216,171,105,0.06)', borderTop: '1px solid rgba(216,171,105,0.15)', borderBottom: '1px solid rgba(216,171,105,0.15)', padding: '24px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 24 }}>
          {[
            { label: 'Pass 1 — Generation', desc: 'Claude generates 4 variants per position using only behavioral language.' },
            { label: 'Pass 2 — Scoring', desc: 'GPT-4 scores each variant blind across 4 bias dimensions (0–100).' },
            { label: 'Pass 3 — Selection', desc: 'Claude selects the lowest-bias, most accessible neutral variant.' },
          ].map(step => (
            <div key={step.label}>
              <p style={{ color: '#D8AB69', fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 4 }}>{step.label}</p>
              <p style={{ color: 'rgba(245,240,232,0.5)', fontSize: 13, lineHeight: 1.55, margin: 0 }}>{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Questions */}
      <section style={{ backgroundColor: '#0F1B1F', padding: '48px 24px 80px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          {questions.length === 0 ? (
            <div style={{ padding: '60px 0', textAlign: 'center' }}>
              <p style={{ color: 'rgba(245,240,232,0.4)', fontSize: 16 }}>No approved questions yet. The pipeline is being seeded.</p>
              <p style={{ color: 'rgba(245,240,232,0.25)', fontSize: 13, marginTop: 8 }}>Check back soon — questions are generated continuously as candidate data is verified.</p>
            </div>
          ) : (
            questions.map((q, i) => (
              <div key={q.id} style={{ borderTop: '1px solid rgba(216,171,105,0.1)', padding: '32px 0' }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12, marginBottom: 16 }}>
                  <div>
                    <p style={{ color: '#D8AB69', fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 4 }}>
                      {q.race.label} · {TOPIC_LABELS[q.topic] || q.topic}
                    </p>
                    <p style={{ color: '#F5F0E8', fontSize: 18, fontWeight: 400, lineHeight: 1.4, margin: 0, maxWidth: 720 }}>
                      {q.questionText}
                    </p>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <p style={{ color: 'rgba(245,240,232,0.3)', fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 4 }}>Bias Score</p>
                    <p style={{ color: q.biasScore < 20 ? '#81C784' : q.biasScore < 40 ? '#D8AB69' : '#E57373', fontSize: 28, fontWeight: 700, margin: 0, lineHeight: 1 }}>
                      {q.biasScore != null ? Math.round(q.biasScore) : '—'}
                    </p>
                    <p style={{ color: 'rgba(245,240,232,0.25)', fontSize: 10, marginTop: 2 }}>lower = more neutral</p>
                  </div>
                </div>

                {/* Bias breakdown */}
                {q.biasScore != null && (
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 24, marginBottom: 20 }}>
                    <div>
                      <BiasBar label="Loaded Language" value={q.loadedLanguage} />
                      <BiasBar label="False Equivalence" value={q.falseEquivalence} />
                    </div>
                    <div>
                      <BiasBar label="Asymmetric Framing" value={q.asymmetricFraming} />
                      <BiasBar label="Cultural Assumption" value={q.culturalAssumption} />
                    </div>
                  </div>
                )}

                {/* Source position */}
                {q.position?.stance && (
                  <div style={{ backgroundColor: 'rgba(255,255,255,0.03)', borderLeft: '2px solid rgba(216,171,105,0.3)', padding: '10px 14px', marginBottom: 16, borderRadius: '0 4px 4px 0' }}>
                    <p style={{ color: 'rgba(245,240,232,0.3)', fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 4 }}>Source Position</p>
                    <p style={{ color: 'rgba(245,240,232,0.55)', fontSize: 13, lineHeight: 1.5, margin: 0 }}>{q.position.stance}</p>
                    <p style={{ color: 'rgba(245,240,232,0.25)', fontSize: 11, marginTop: 4 }}>{q.position.sourceType?.replace(/_/g, ' ')}</p>
                  </div>
                )}

                {/* All variants */}
                {q.variants.length > 1 && (
                  <details style={{ marginTop: 8 }}>
                    <summary style={{ color: 'rgba(216,171,105,0.6)', fontSize: 12, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', cursor: 'pointer', userSelect: 'none' }}>
                      {q.variants.length} variants generated ({q.variants.length - 1} rejected) →
                    </summary>
                    <div style={{ marginTop: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {q.variants.map((v, vi) => (
                        <div key={v.id} style={{ padding: '12px 14px', backgroundColor: v.selected ? 'rgba(216,171,105,0.06)' : 'rgba(255,255,255,0.02)', borderRadius: 6, border: `1px solid ${v.selected ? 'rgba(216,171,105,0.25)' : 'rgba(255,255,255,0.06)'}` }}>
                          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                            <span style={{ color: v.selected ? '#D8AB69' : 'rgba(245,240,232,0.3)', fontSize: 10, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase' }}>
                              {v.selected ? '✓ Selected' : `Variant ${vi + 1}`}
                            </span>
                            {v.biasScore != null && (
                              <span style={{ color: 'rgba(245,240,232,0.4)', fontSize: 11 }}>Score: {Math.round(v.biasScore)}</span>
                            )}
                          </div>
                          <p style={{ color: v.selected ? 'rgba(245,240,232,0.8)' : 'rgba(245,240,232,0.4)', fontSize: 13, lineHeight: 1.55, margin: 0, textDecoration: v.selected ? 'none' : 'none' }}>
                            {v.variantText}
                          </p>
                        </div>
                      ))}
                    </div>
                  </details>
                )}
              </div>
            ))
          )}
        </div>
      </section>

      {/* Footer CTA */}
      <section style={{ backgroundColor: '#F5F0E8', padding: '60px 24px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 24 }}>
          <div>
            <p style={{ color: '#0F1B1F', fontSize: 17, fontWeight: 400, marginBottom: 4 }}>Academic reviewers and civic partners welcome.</p>
            <p style={{ color: 'rgba(15,27,31,0.5)', fontSize: 14 }}>The full methodology white paper is available on request.</p>
          </div>
          <div style={{ display: 'flex', gap: 12 }}>
            <a href="/methodology" style={{ backgroundColor: '#0F1B1F', color: '#D8AB69', padding: '12px 24px', borderRadius: 6, fontSize: 13, fontWeight: 700, textDecoration: 'none' }}>Read the Methodology</a>
            <a href="/contact" style={{ backgroundColor: 'transparent', color: '#0F1B1F', padding: '12px 24px', borderRadius: 6, fontSize: 13, fontWeight: 700, textDecoration: 'none', border: '1px solid rgba(15,27,31,0.2)' }}>Contact the Team</a>
          </div>
        </div>
      </section>
    </>
  )
}
